### ISSUE TITLE
Put `options.lua` in a top-level runtime folder (`plugin`) instead of using require 

### ISSUE THREAD

**Issue by shaunsingh** [siduck76/NvChad#175]
**Is your feature request related to a problem? Please describe.**
I know you like to be *as* optimized as possible. Not really an issue, just a way something could be done better

**Describe the solution you'd like**
Put the `options.lua` file, which is currently `require`d, under a `/plugin` directory at the root of the project. It is much faster than require because it does not perform search and results are not cached (and you want this behavior, because it just settings that loaded once)

You can also try putting the other files asynchronously as loaded on runtime (mappings, theme, bufferline) and see if it speeds anything up

**Describe alternatives you've considered**
Just an idea

**Additional context**
You can read more runtime files here: https://github.com/neovim/neovim/pull/14686

**Comment by shaunsingh** [comment]
I just tested it. It increases the result given by `:St` (up from 2ms to 8ms) but it decreases the result given by `hyperfine "nvim +q"` (down from 38ms to 29ms)

**Comment by shaunsingh** [comment]
Actually, you should do this for all the files you currently asynchronously load. Since Lua is still single threaded, you are actually just delaying the loading of those files and fooling the Profiler, putting it under `plugin` will decrease actual startuptime, but increase the one displayed by `:St` as its not fooled anymore.

**Comment by siduck76** [comment]
> **Is your feature request related to a problem? Please describe.**
> I know you like to be _as_ optimized as possible. Not really an issue, just a way something could be done better
> 
> **Describe the solution you'd like**
> Put the `options.lua` file, which is currently `require`d, under a `/plugin` directory at the root of the project. It is much faster than require because it does not perform search and results are not cached (and you want this behavior, because it just settings that loaded once)
> 
> You can also try putting the other files asynchronously as loaded on runtime (mappings, theme, bufferline) and see if it speeds anything up
> 
> **Describe alternatives you've considered**
> Just an idea
> 
> **Additional context**
> You can read more runtime files here: [neovim/neovim#14686](https://github.com/neovim/neovim/pull/14686)

sounds cool , maybe @Akianonymus can implement it

**Comment by siduck76** [comment]
@shaunsingh probably a dumb question : would it be a bad thing if we put the whole config in runtime?

**Comment by shaunsingh** [comment]
@siduck76 Whatever isn't lazy loaded (which I believe are the files in `init.lua`) are the only files that benefit from being runtime files. Anything loaded by packer is already under /pack or /opt, which are the fastest places. I recommend keeping the rest of the config in runtime.

**Comment by shaunsingh** [comment]
If its good with you, I'll make a quick pr and profile it

**Comment by siduck76** [comment]
> If its good with you, I'll make a quick pr and profile it

yeah sure!

**Comment by Akianonymus** [comment]
>Actually, you should do this for all the files you currently asynchronously load. Since lua is still single threaded, ...

About lua in nvim being single threaded, and async loading and whatnot ( credits to a post on neovim reddit )

**NeoVim uses an event loop via the libuv library. 
Libuv provides the APIs for doing asynchronous I/O, but under the hood it still makes use of a pool of threads to do it. 
So it is still technically multi threaded, but it's all abstracted away and NeoVim doesn't do the thread management.**

And what are we using for async loading, `vim.loop.new_async`, a libuv function.

Even if you don't believe me if all of that is still happening, move `options.lua` to async block. If it isn't multi threaded, and runs sequentially, then the config should load without any error, but it won't because some plugin will say this and that missing ( for ex `vim.g.nvchad_theme` will be missing and highlight won't work as desired ).

---
> I just tested it. It increases the result given by :St (up from 2ms to 8ms) but it decreases the result given by `hyperfine "nvim +q"` (down from 38ms to 29ms)

About that, yes. startup time plugin in nv chad is a total placebo stuff and doesn't reflect real time taken (as i have already said that in some other discussion too ).

Good to see that you are using hyperfine, but you are using it the wrong way.

`nvim +q `is faulty way to benchmark neovim. from the help page


```
+<cmd>, -c <cmd>      Execute <cmd> after config and first file
```

So, it doesn't wait for plugin loading, autocmds and whatever, just load init.lua and show file then quickly quit because of +q. To test this, run `nvim init.lua +q` ( and boom, the error appears, even the stuff in plugin folder is not loaded at that time ).

Adding to this, when using hyperfine, use -r to specify the number of times it should run and --warmup, for consistency.

To test with hyperfine properly, use this

```
# do warmup as sometimes neovim take time for loading ( for potato laptops )
hyperfine --warmup 5 -r 20 "nvim +'autocmd BufReadPost * ++once quitall'"
```
This will enter neovim and after the buffer is loaded properly, quit it.

---
So, i tried benchmarking it, just moving `options.lua` to plugin folder and removing from `init.lua`. Rather than decreasing the time taken, it increased.

Before:

```
❯ hyperfine --warmup 5 -r 20 "nvim +'autocmd BufReadPost * ++once quitall'"
Benchmark #1: nvim +'autocmd BufReadPost * ++once quitall'
  Time (mean ± σ):     359.3 ms ±  26.6 ms    [User: 163.8 ms, System: 57.8 ms]
  Range (min … max):   315.9 ms … 400.0 ms    20 runs
```

After:
```
❯ hyperfine --warmup 5 -r 20 "nvim +'autocmd BufReadPost * ++once quitall'"
Benchmark #1: nvim +'autocmd BufReadPost * ++once quitall'
  Time (mean ± σ):     402.6 ms ±  51.0 ms    [User: 195.0 ms, System: 61.6 ms]
  Range (min … max):   327.2 ms … 504.4 ms    20 runs
```

Yes, i tried it mutiple times to test if this is some coincidence, but nope. Maybe i am doing something wrong in changing the config.

**Comment by siduck76** [comment]
> ```
> hyperfine --warmup 5 -r 20 "nvim +'autocmd BufReadPost * ++once quitall'"
> ```

yes nvim +q might not be the proper way to benchmark but it should technically work , like whenever we open a file , we expect the nvim window to load up fast right?  idc  much about the startuptime but I want to see nvim opening its window fast af! Also no one enters in the insert mode directly after the moment nvim loads xD like nvim opens at 0.5s , none would just start editing his file right away xD. So what matters most is how fast nvim window opens

**Comment by Akianonymus** [comment]
@siduck76 How about reading my long ass explanation rather than just saying anything, no offense.

As i said, gonna say it again, nvim +q doesn't load all the stuff for atleast entering the nvim window, so no, it doesn't show the stats with your config. It will show the stat for some half baked neovim state which you never have.

Also, read how BufReadPost works ( assuming you don't know ), also you can use VimEnter too for testing.

**Comment by shaunsingh** [comment]
> NeoVim uses an event loop via the libuv library.
Libuv provides the APIs for doing asynchronous I/O, but under the hood it still makes use of a pool of threads to do it.
So it is still technically multi threaded, but it's all abstracted away and NeoVim doesn't do the thread management.

Assuming you're using proper multi threading in lua, wouldn't there be issues with mismatched lua states between the files, giving a nice plethora of errors? You aren't using a pool of threads, you're tricking the compiler (or jit) into doing another task when its idle. While the compiler still thinks in terms of threads, its still all running on one thread 

Running it asynchronously only defers the loading of the three files. There shouldn't be any benefit to loading those files asynchronously because neovim isn't doing anything else 

> Even if you don't believe me if all of that is still happening, move options.lua to async block. If it isn't multi threaded, and runs sequentially, then the config should load without any error, but it won't because some plugin will say this and that missing ( for ex vim.g.nvchad_theme will be missing and highlight won't work as desired ).

That doesn't really prove anything? Single threaded async is still deferred to that first "tick" of neovim. Your theme is loaded instantly after packer, meanwhile the options file is loaded "when neovim gets the time," which understandably means that you can have missing options that something requires. This is only another case of why *not* to use async 

> Good to see that you are using hyperfine, but you are using it the wrong way.

I see that as well. However `❯ hyperfine --warmup 5 -r 20 "nvim +'autocmd BufReadPost * ++once quitall'"` is still incorrect, because with this async config, you're still loading nessecary files (includding mappings) after BufRead, even when packer has started working on it. The reason you don't notice it is because the whole config still loads in under 60ms or so, but if you ask hyperfine to quit instantly, of course its going to skip the loading of those files. 

 > So, i tried benchmarking it, just moving options.lua to plugin folder and removing from init.lua. Rather than decreasing the time taken, it increased.
 
 Looks like the range for the second benchmark is twice as high as the first one. If you look at the min timings its a 12ms difference, which is slightly faster than the total startuptime to load the files *before* you implemented this async crap.. Sounds about right to me 
 
 > How about reading my long ass explanation rather than just saying anything, no offense.
 
 @siduck76 's goal is actually the opposite of mine I believe. I prefer the user to have the fastest "real-world" startuptime, siduck prefers neovim to load the ui as fast as possible, which async does solve but bring a lot of complications with it. To test his preference, you need to test on the initial vimenter

**Comment by shaunsingh** [comment]
https://www.youtube.com/watch?v=GToxQKi7LZg&feature=youtu.be

I highly recommend giving this a watch.

**Comment by Akianonymus** [comment]
@shaunsingh 

I already looked into all that. I already have commits, will pr soon.

https://github.com/Akianonymus/NvChad/commits/main

Obviously this is partially my fault i added it without much thinking and not benchmarking properly, but i blame faulty startuptime plugin, xD.

And BufReadPost should be enough, because it gets activated after a buffer is loaded, if i am understanding correctly.

**Comment by shaunsingh** [comment]
> I already looked into all that. I already have commits, will pr soon.

Looks good to me then. Thanks for all the work on this project, I'm loving the config :)

**Comment by siduck76** [comment]
@shaunsingh less startuptime by any means == faster load in nvim ui :D

**Comment by Akianonymus** [comment]
> > I already looked into all that. I already have commits, will pr soon.
> 
> Looks good to me then. Thanks for all the work on this project, I'm loving the config :)

About why this issue was created, moving files to plugin folder. It does make sense that if we don't use require then it shouldn't need to search for files and should be faster, but somehow it slows on hyperfine.

Also, about the searching that require does, i think there shouldn't be much actual searching because the given file is just available right there in the root folder. And according to lua docs, require first looks for the file in the same folder.

**Comment by siduck76** [comment]
the async stuff makes the startuptime faster by 6-7ms , Loading NVIM UI faster is also essential

**Comment by shaunsingh** [comment]
@siduck76 Well yes but actually now. Although it appears through benchmarking (`:St`) that async would be faster, its actually just neglecting to see the loading of that async lua code, as that isn't visible to vimscript. 

My theory was that moving those files to a runtime folder, which would avoid neovim searching and caching them, should make startuptime ever so slightly faster. However, it somehow made it slower. 

@Akianonymus made a better method for loading files which should work correctly
