### ISSUE TITLE
Newbie friendly/descriptive which-key +prefix

### ISSUE THREAD

**Issue by AndreasPB** [siduck76/NvChad#1852]
**Is your feature request related to a problem? Please describe.**
I'm new to NvChad and don't have the key mappings in my muscle-memory yet, so I rely heavily on NvChad's which-key. The undescriptive `+prefix` leads to a lot of "I wonder what that is" instead having an idea of what to expect.

**Describe the solution you'd like**
I feel like changing the `+prefix` to something more descriptive would make it easier to navigate. Like for example `+git` for the `g`-prefix, still using the `+` to indicate the prefix, but removing the guesswork.

**Describe alternatives you've considered**
Becoming a power-user and not needing which-key (working on it ;D)

**Additional context**
I love this config

**Screenshot**
![image](https://user-images.githubusercontent.com/43907402/227475224-32e8dd14-1c23-4f52-b70a-cf6290101647.png)

**Comment by siduck** [comment]
hi there @AndreasPB  for example not all <leader>g* mappings would use git stuff and same with other prefixes. I suggest you to just add the change in your config instead :)

add this in your custom plugins table. 

```lua
  {
    "folke/which-key.nvim",
    config = function(_, opts)
      -- default config function's stuff
      dofile(vim.g.base46_cache .. "whichkey")
      require("which-key").setup(opts)
      
      -- your custom stuff
      require("which-key").register({
        f = { name = "file" },
        g = { name = "git" },
      }, { prefix = "<leader>" })
    end,
  },
```

**Comment by datner** [comment]
@siduck its fine to prefer emacs-style chords instead of domain tree access, but maybe intuition helpers would go a long way? 
For example how `ciw` is mentally read as `Change In Word`, so `<leader>gc` is `Git Commit` and `<leader>th` is `THemes` and so on

**Comment by siduck** [comment]
> @siduck its fine to prefer emacs-style chords instead of domain tree access, but maybe intuition helpers would go a long way? For example how `ciw` is mentally read as `Change In Word`, so `<leader>gc` is `Git Commit` and `<leader>th` is `THemes` and so on

yes its fine

**Comment by datner** [comment]
@siduck sorry I didn't quite understand? I meant adding these to the docs or writing a sentence about it somewhere

**Comment by siduck** [comment]
> @siduck sorry I didn't quite understand? I meant adding these to the docs or writing a sentence about it somewhere

i dont think docs are needed for it. mappings description can be anything. 

for example :  most of our telescope mappings start from "f" cuz we use telescope for finding and most of their descriptions have the keyword "find"

**Comment by gitaarik** [comment]
If mappings on a certain prefix are not grouped, would it make sense to show the keybindings in the start page?

So like:

```
/ -> Toggle comment
b -> New buffer
[..]
ff -> Find files
fa -> Find all
fw -> Live grep
[..]
td -> Toggle deleted
th -> Nvchad themes
```

Then at least you have an overview of all the keybindings without having to try out all the prefixes to find what you are looking for.

**Comment by gitaarik** [comment]
But yeah I think that behavior is not possible with which-key atm. Personally I maybe find it useful to group the mappings in certain prefixes, so they make logical sense, and you can name the prefix groups, so it is easier to get to know the keybindings when you're staring out.

I'm trying that out now with my current setup, but I notice I need to disable some default NvChad keymappings for that, otherwise some prefix groups won't show up in the which-key menu. I didn't find an easy way to disable default keybindings, and now I'm loading a custom plugin which doesn't lazy load and uses `vim.defer_fn()` before unsetting default mappings with `vim.cmd("unmap <leader>h")` for example. It works though and I'm setting up my grouped keybindings and see how that works out :).

```lua
vim.defer_fn(function()
  -- Disable nvterm horizontal terminal, used for Help prefix
  vim.cmd("unmap <leader>h")
end, 0)
```

Not sure why the `defer_fn()` is necessary, but it is, and it seems to work fine.

**Comment by siduck** [comment]
@gitaarik use M.disabled to disable nvchad plugins, it totally removes the mapping

**Comment by gitaarik** [comment]
I don't want to disable plugins, just some default keymappings. For example, I want to use the built-in `nvim-lspconfig` plugin, but I don't want to use the default keymapping for LSP code action `<leader>ca`, because in my config I map it to `<leader>la` because I have all my LSP keymaps under the `l` prefix. And I want to use the `c` prefix for something else.

I noticed that some mappings for plugins that have `plugin = true` in `lua/core/mappings.lua` are not yet set when I try to unmap them in my custom plugin. But if I first override them first in my `lua/custom/mappings.lua`, then I can unset them in my custom plugin. A bit of a hassle, but it works. It does mess up the cheat sheet however.

**Comment by siduck** [comment]
@gitaarik sorry my typo, M.disabled disables nvchad mappings

**Comment by gitaarik** [comment]
Aha ok, and where should I put this? In the root of the chadrc table?

**Comment by siduck** [comment]
> Aha ok, and where should I put this? In the root of the chadrc table?

in your mappings table https://nvchad.com/docs/config/mappings

**Comment by gitaarik** [comment]
Ah awesome, that works great! I was looking for that but I didn't find it ;).

However I don't seem to be able to disable the `<C-s>` and `<C-c>` keybindings. My muscle memory for `<C-c>` to exit insert mode or cancel some operation is too ingrained ;). And I rather use `<leader>w` to write the file. Not sure why I can't disable these keybindings, because everything in `lua/core/utils.lua` in `remove_disabled_keys()` seems to go well.

**Comment by gitaarik** [comment]
Sorry, this was an error on my side, I had the original `<C-s>` keybinding in my config. Removed it; it works :+1:
