### ISSUE TITLE
Why does NvChad hasn't a git client like fugitive?

### ISSUE THREAD

**Issue by di3goleite** [siduck76/NvChad#2210]
Hello, I'm new in the NvChad world. Firstly I would like to thank you to everybody that's working on this amazing project. I trully loved it.

So, I want to know why does NvChad hasn't a git client like fugitive? There is any post describing the whys about this decision? Besides that, do you folks recommend any tutorial describing how to setup fugitive on NvChad (I was able to install the plugin but seems it is not working here)?

**Comment by antoineco** [comment]
The reason is simply that NvChad is very minimal and tries to bring only these two things: a nice UI, and a minimal set of sensible base plugins. Not everybody needs to interact with Git from within a text editor, so that choice is left to the user.

Regarding your issue: if you installed fugitive using Lazy.nvim (the standard way in NvChad), the plugin will be loaded lazily (only when it's actually being used). This works out of the box with _some_ plugins, but a majority of plugins need to be enabled explicitly for specific filetypes, or on certain events or commands. For example, the following config enables fugitive when specific commands are executed:

```lua
---@type NvPluginSpec[]
local plugins = {
  {
    "tpope/vim-fugitive",
    cmd = { "Git", "Gedit", "Gsplit", "Gdiffsplit" },
  }.
}

return plugins
```

If you don't know in advance all commands you might be using to trigger that plugin, the best is probably to instruct Lazy to load it unconditionally:

```lua
---@type NvPluginSpec[]
local plugins = {
  {
    "tpope/vim-fugitive",
    -- you can use the VeryLazy event for things that can
    -- load later and are not important for the initial UI
    event = "VeryLazy",
    -- or you can load the plugin immediately (small performance hit on startup time)
    lazy = false,
  }.
}

return plugins
```

I would recommend ` event = "VeryLazy",` for this particular plugin.

**Comment by di3goleite** [comment]
Thank you so much for all the context you provided in this answer. I explains all my doubts! ❤️ 

I just want to make one suggestion: would be nice to have an about page on the project website. There, besides general project overview, we could have a motivation section describing more or less what you wrote on the first paragraph of this answer. This can help a lot of new people.

**Comment by antoineco** [comment]
@siduck is the author of the project and website, I'm just providing my interpretation as a (power?) user. But I agree, maybe the intent needs to be more clear, so that people can tell what differentiates NvChad from other popular Neovim configs.

The project's README explains some of that already I feel. Did you check it out?

**Comment by di3goleite** [comment]
No. I didn't check the README, because I came directly from the website. The README is pretty clear about it, so you're right. The website is missing this information, so I think would be welcome to have this about section or page on the website.

Thank you a lot for all the clarification.
