### ISSUE TITLE
NvChad dosn't fill terminal window (alacritty)

### ISSUE THREAD

**Issue by VinjarBerland** [siduck76/NvChad#2216]
![image](https://github.com/NvChad/NvChad/assets/65012935/fa6694a9-879d-4894-b4e9-647b01b452d0)

**Comment by antoineco** [comment]
It's not NvChad that doesn't fill the window, it's (Neo)vim.

Two things are happening here:

- Your terminal emulator has some frame applied by default around the screen (otherwise your shell would look very very bad).
- The bottom row is lower than the height of your font, so that space can't be used by the application (vim).
