### ISSUE TITLE
Failed to update lewis6991/gitsigns.nvim

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#224]
Running PackerUpdate / PackerSync is failing to update gitsigns.nvim

**Comment by JustSage** [comment]
If packer fails to update `X` plugin it means there was a flawed `--force push` to the master branch of `X` plugin.
It will not break the plugin but packer won’t update the new commits.
You can open an issue in the relative plugin repo or in packer.nvim.

This issue is not related to NvChad’s configurations.
