### ISSUE TITLE
Warning: multiple different client offset_encodings detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by qvc0** [siduck76/NvChad#2316]
**Describe the bug**
Warning: multiple different client offset_encodings detected for buffer, this is not supported yet

Steps To reproduce the behavior:
1. Install NvChad with example custom config
2. Write a code in .c or .cpp file
3. See error

I use Void GNU/Linux, kitty term, last version of nvim(0.9.1)

**Additional context**
This error only appears when I use example custom config.

**Comment by siduck** [comment]
not a nvchad issue, pls configure your clangd lsp settings in custom lspconfig

**Comment by ImranAvenger** [comment]
@siduck I'm facing same issues like @LazyMaksim. When I code in C/C++, this `Warning: multiple different client offset_encodings detected for buffer, this is not supported yet` message appears. So how to configure clangd lsp settings in custom lspconfig? You can ask me more questions, I will try my best to reply with step by step. I've spent a lot of time for it... Thank you...

**Comment by siduck** [comment]
@ImranAvenger this is a common issue, just google it and you'll see posts of r/neovim and please seek help in our discord server or telegram group

**Comment by ImranAvenger** [comment]
@siduck I'm happy for your reply... Could you please provide me telegram group link here?

**Comment by JeremiahCheatham** [comment]
If anyone is still stuck on this like me let me give the best answer so far i could find since someone above refused to offer a helpful answer.

This issue has something to do with clangd and null-ls or something I don't actually understand because i am not a neovim/nvchad expert or developer. The fix seems to be having them correctly configured. Since i am using the completely stock nvchad out of the box it is configued for cpp or should i say not correctly configured for cpp since we are having this bug. So if someone says this is not an nvchad bug they are not being truthful since it has to do with neovim being incorrectly configured as it is in nvchad. I spent some time googling this problem way too much time. Then i stumbled upon this post with the standard answer of go as the question somewhere else. So i went back to googling way to much more and found that I need to edit null-ls files that don't exist or json files. The closest answer i could find was someone claiming that it was not an answer but a temporary hack. https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428#issuecomment-997226723

in custom->config->lspconfig.lua at the top you need to add this line. Change this.
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
```
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
capabilities.offsetEncoding = { "utf-16" }
```

Since i feel this is not the correct answer i would ask someone to give the real correct answer. That is someone who actually knows the answer to you know answer. And all those who don't know the answer to not answer at all. Also telling someone to google it when they already have is not helpful at all.

**Comment by sudo-ghost** [comment]
> If anyone is still stuck on this like me let me give the best answer so far i could find since someone above refused to offer a helpful answer.
> 
> This issue has something to do with clangd and null-ls or something I don't actually understand because i am not a neovim/nvchad expert or developer. The fix seems to be having them correctly configured. Since i am using the completely stock nvchad out of the box it is configued for cpp or should i say not correctly configured for cpp since we are having this bug. So if someone says this is not an nvchad bug they are not being truthful since it has to do with neovim being incorrectly configured as it is in nvchad. I spent some time googling this problem way too much time. Then i stumbled upon this post with the standard answer of go as the question somewhere else. So i went back to googling way to much more and found that I need to edit null-ls files that don't exist or json files. The closest answer i could find was someone claiming that it was not an answer but a temporary hack. [jose-elias-alvarez/null-ls.nvim#428 (comment)](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428#issuecomment-997226723)
> 
> in custom->config->lspconfig.lua at the top you need to add this line. Change this.
> 
> ```
> local on_attach = require("plugins.configs.lspconfig").on_attach
> local capabilities = require("plugins.configs.lspconfig").capabilities
> ```
> 
> ```
> local on_attach = require("plugins.configs.lspconfig").on_attach
> local capabilities = require("plugins.configs.lspconfig").capabilities
> capabilities.offsetEncoding = { "utf-16" }
> ```
> 
> Since i feel this is not the correct answer i would ask someone to give the real correct answer. That is someone who actually knows the answer to you know answer. And all those who don't know the answer to not answer at all. Also telling someone to google it when they already have is not helpful at all.

this worked thank you very much
