### ISSUE TITLE
alt doesn't work on macos

### ISSUE THREAD

**Issue by cbingb666** [siduck76/NvChad#2385]
**Describe the bug**
I'm using alt + v to switch vertical term on macos and it's not working.

**To Reproduce**
1. Press alt + v

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - Operating System：macos
 - Terminal：alacritty
 - Version of Neovim: v0.9

**Additional context**
-

**Comment by siduck** [comment]
terminal issue, use something better like alacritty wezterm kitty

**Comment by BLumia** [comment]
> Terminal：alacritty

> use something better like alacritty wezterm kitty

I'm confused, the original person reports this issue claims that alacritty is used, and you are suggesting alacritty as a "better" alternative, which doesn't make sense.

I'm also facing this issue but I'm using iTerm2, I guess maybe I should try WezTerm or Kitty instead. But anyway I guess maybe then we should avoid suggesting iTerm2 here https://nvchad.com/docs/faq/#nvchad's_color_is_weird ?

**Comment by siduck** [comment]
every time i see this issue i suggest cross platform terms as they got better defaults. didnt see he said alacritty i missed it! 

Just enable alt in whatever terminal or OS you're using

**Comment by BLumia** [comment]
After some googling, I found the solution for iTerm2. See [this stackoverflow answer](https://stackoverflow.com/a/78322336/5785726).

By the way, I can confirm WezTerm also work. I don't plan to try if alacritty works so at least switching to WezTerm can also be a solution :)

I'm posing both answers here since this issue itself is one of the search result while I'm looking for solution, so it could hopefully help other people that having the same issue as mine :)

**Comment by siduck** [comment]
> After some googling, I found the solution for iTerm2. See [this stackoverflow answer](https://stackoverflow.com/a/78322336/5785726).
> 
> By the way, I can confirm WezTerm also work. I don't plan to try if alacritty works so at least switching to WezTerm can also be a solution :)
> 
> I'm posing both answers here since this issue itself is one of the search result while I'm looking for solution, so it could hopefully help other people that having the same issue as mine :)

there's ghosty terminal too
