### ISSUE TITLE
Adding gruvbox theme

### ISSUE THREAD

**Issue by cvignal** [siduck76/NvChad#59]
Hello, I'm really digging your config but my setup is gruvbox-based and I have a bit of trouble converting your setup to a full gruvbox theme. I have changed the theme loaded by base16 and tried to replicate your onedark.lua with different colors but it's not working as I'd like. Do you intend do add support for other colorschemes ?

**Comment by siduck76** [comment]
If you could wait a bit then I could add the gruvbox theme at this months ending , NvChad will support more themes but its gonna take some time , since my custom onedark has 26+colors  and and those colors don't follow the original onedark theme , it's a mix of nord and some pastel. The base16 plugin mostly changes syntax colors.

**Comment by siduck76** [comment]
@cvignal is this ok?  you can change syntax theme easily , this is nvchad's modified version of material gruvbox.

![image](https://user-images.githubusercontent.com/59060246/122990970-21da4180-d3c2-11eb-8364-ae63d3582272.png)

**Comment by isquack** [comment]
![Uploading IMG_20210623_193528.jpg…]()

**Comment by siduck76** [comment]
> wheres the colors for that theme?

Im gonna add it soon :)

**Comment by cvignal** [comment]
@siduck76 yeah it looks great, ping me when you add it to the repo :)

**Comment by siduck76** [comment]
@cvignal  https://github.com/siduck76/NvChad/wiki#themes

**Comment by ashincoder** [comment]
please close the issue as it is added
